default:
  image: ruby:3.2

script:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build

job:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build

deploy-pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  pages: true  # specifies that this is a Pages job

  
